import zlib
from typing import Any, Callable, Dict, List

# A handful of common, unambiguously-real Minecraft ids used to build a
# not-a-member question below. Deliberately spans blocks/items/mobs rather
# than being tag-specific -- the goal is a distractor that's plausible
# enough to require an actual membership check, not a maximally hard
# adversarial choice.
_TAG_DISTRACTOR_POOL: List[str] = [
    "minecraft:dirt", "minecraft:stone", "minecraft:oak_planks", "minecraft:cobblestone",
    "minecraft:diamond_sword", "minecraft:iron_pickaxe", "minecraft:water_bucket", "minecraft:torch",
    "minecraft:crafting_table", "minecraft:furnace", "minecraft:bread", "minecraft:zombie",
    "minecraft:creeper", "minecraft:oak_log", "minecraft:glass", "minecraft:redstone",
]


def _tag_non_member_question(f: Dict[str, Any]) -> str:
    members = set(f["fields"]["members"])
    candidates = [c for c in _TAG_DISTRACTOR_POOL if c not in members] or _TAG_DISTRACTOR_POOL
    # crc32 rather than the builtin hash(): deterministic across processes
    # (hash() is salted per-run), so the same fact always gets the same
    # distractor without needing an rng threaded through this call site.
    distractor = candidates[zlib.crc32(f["subject_id"].encode()) % len(candidates)]
    return f"Is {distractor} a member of the tag {f['subject_id']}?"


ARCHETYPES: Dict[str, List[Callable[[Dict[str, Any]], str]]] = {
    # Only the forward "how do I craft X" question: subject_id -> its
    # ingredients is always single-valued. The reverse "what does crafting
    # <ingredients> produce?" was removed -- it is ambiguous for single-input
    # recipes (one block stonecuts into many variants), so the teacher
    # correctly refuses while the structured_claim still passes the field diff,
    # admitting a refusal non-answer (36% of the fact lane in a spot check).
    "recipe": [
        lambda f: f"What items do you need to craft {f['subject_id']}?",
    ],
    "loot_table": [
        lambda f: f"What can {f['subject_id']} drop?",
    ],
    "advancement": [
        lambda f: f"What criteria unlock the advancement {f['subject_id']}?",
    ],
    # Two entries, picked ~50/50 by pick_archetype's rng.choice: the fact's
    # own fields.members[0] is always a true member, so a tag archetype list
    # of only that lambda has zero negative examples across the whole
    # corpus -- verified against a real generated dataset, every one of its
    # tag rows had answer "Yes", and the resulting fine-tune learned to
    # answer "Yes" to tag questions unconditionally (confirmed by testing
    # known-false memberships). The second lambda is the fix.
    "tag": [
        lambda f: f"Is {f['fields']['members'][0]} a member of the tag {f['subject_id']}?",
        _tag_non_member_question,
    ],
    "worldgen_structure": [
        lambda f: f"What biome does the structure {f['subject_id']} generate in?",
    ],
    "enchantment": [
        lambda f: f"What is the maximum level of the enchantment {f['subject_id']}?",
        lambda f: f"Which equipment slot(s) does the enchantment {f['subject_id']} apply in?",
    ],
    "villager_trade": [
        lambda f: f"In the villager trade {f['subject_id']}, what item and how many does the villager want?",
        lambda f: f"In the villager trade {f['subject_id']}, what does the villager give in return?",
    ],
    "jukebox_song": [
        lambda f: f"How many seconds long is the music disc {f['subject_id']}?",
    ],
    "painting_variant": [
        lambda f: f"What are the block dimensions (width by height) of the {f['subject_id']} painting?",
    ],
}

FREE_RECALL_TOPICS: List[str] = [
    "Early-game strategy: fastest route to obsidian",
    "Efficient early-game food farming",
    "Redstone: building a basic automatic door",
    "Nether survival: navigating without dying to lava",
    "End-game preparation: gearing up for the Ender Dragon",
    "Villager trading: getting the best early trades",
    "Base defense against nighttime mobs",
    "Efficient strip-mining for diamonds",
    "Enchanting: getting the most useful enchantments early",
    "Potion brewing: building a basic brewing setup",
    "Animal farming: breeding and housing livestock efficiently",
    "Building a mob grinder for experience and drops",
    "Exploring the End beyond the dragon fight",
    "Ocean survival: exploring and building underwater",
    "Building an efficient item storage and sorting system",
    "Gearing up for PvP combat",
    "Finding and using ancient debris for netherite",
    "Transportation: building an efficient rail or elytra route",
    "Setting up a raid farm",
    "Choosing an efficient base location and layout",
    "Fishing for early-game resources and enchanted gear",
    "Taming and using wolves, cats, and other tameable mobs",
    "Building an iron farm",
    "Using maps and exploration to find structures efficiently",
    "Fighting and defeating the Wither boss",
    "Bartering with piglins for gold ingots",
    "Building a beacon and choosing beacon effects",
    "Elytra flight: using fireworks to boost distance",
    "Building an ender pearl stasis chamber",
    "Automating sugar cane or bamboo farming",
    "Bee farming: collecting honey safely",
    "Surviving and navigating the Deep Dark biome",
    "Avoiding or dealing with the Warden",
    "Exploring a Trial Chamber",
    "Horse breeding and finding high-stat horses",
    "Building a TNT cannon",
    "Copper mechanics: oxidation and lightning rods",
    "Using an Allay to automate item collection",
    "Archaeology: excavating suspicious sand and gravel",
    "Building a simple redstone computer or calculator",
    "Trading with wandering traders",
    "Building efficient nether portals for a base network",
    "Farming wither skeleton skulls for a Wither fight",
    "Choosing a good seed or world for a new playthrough",
    "Managing hunger and food efficiently in the mid-game",
    "Building a functional farm in a desert or icy biome",
    "Raiding a pillager outpost safely",
    "Looting a woodland mansion for totems of undying",
    "Exploring an ocean monument for sponges and prismarine",
    "Finding and looting a desert or jungle temple safely",
    "Locating a stronghold and preparing to enter the End",
    "Farming blaze rods at a Nether fortress",
    "Building a guardian farm for prismarine and sponges",
    "Automating wheat, carrot, and potato farms with water and hoppers",
    "Building a villager breeder and trading hall",
    "Choosing between Silk Touch and Fortune for resource gathering",
    "Using a shield effectively in melee combat",
    "Preventing phantoms by managing sleep",
    "Avoiding and surviving creeper explosions",
    "Choosing between a crossbow and a bow for ranged combat",
    "Building a redstone flying machine",
    "Taming and breeding foxes, axolotls, and frogs",
    "Using sculk sensors and sculk shriekers in redstone builds",
    "Collecting shulker shells and using shulker boxes",
    "Setting up an AFK-safe farm using chunk loading",
    "Using tridents with the Riptide and Channeling enchantments",
    "Upgrading netherite gear with smithing templates and applying armor trims",
    "Crossing lava and nether terrain safely using striders",
    "Building an automated tree farm for wood",
    "Setting up a respawn anchor base deep in the Nether",
    "Farming experience efficiently beyond a basic mob grinder",
    "Building and decorating in mangrove swamp or cherry grove biomes",
    "Using camels for fast overland travel and combat",
    "Triggering and surviving a village raid with Bad Omen",
    "Building water or honey block elevators for vertical movement",
    "Using totems of undying and enchanted golden apples for survival",
    "Finding and breeding sniffers to grow ancient plants",
    "Breeding items for cows, sheep, pigs, chickens, and rabbits",
    "Breeding and feeding llamas, turtles, and pandas",
    "Breeding and feeding striders and goats",
    "Combining enchantments and repairing gear with an anvil",
    "Using a grindstone to remove enchantments and repair tools",
    "Setting up a composter for renewable bone meal",
    "Building and using a note block music system",
    "Setting up a lectern and bookshelf enchanting library",
    "Comparing armor materials: leather, iron, gold, diamond, and netherite",
    "Using the mace weapon's Breach and Density enchantments effectively",
    "Fighting the Elder Guardian and removing mining fatigue",
    "Exploring badlands biomes for gold ore and terracotta",
    "Exploring mushroom fields biomes safely",
    "Using banners and loom patterns for decoration",
    "Comparing food items by hunger and saturation value",
    "Building a hidden or secret base entrance",
    "Using scaffolding for safe vertical building",
    "Setting up a slime farm in a swamp biome",
    "Understanding light levels and hostile mob spawning mechanics",
    "Renewable resource farms: cobblestone, stone, and concrete",
    "Fighting endermen without provoking eye contact",
    "Fighting witches and using their potion drops",
    "Raiding an Ancient City safely without triggering the Warden",
    "Fighting evokers and dodging their fang attacks",
    "Looting a shulker box from an End City",
    "Using splash and lingering potions offensively in combat",
    "Choosing bow enchantments: Power, Punch, Flame, and Infinity",
    "Trading with librarians for enchanted books",
    "Destroying end crystals during the Ender Dragon fight",
    "Upgrading diamond armor and tools to netherite using a smithing table",
    "Using observers to trigger redstone contraptions",
    "Building an item sorting system with hoppers and comparators",
    "Building a furnace array for automatic smelting",
    "Building an auto-crafter or dropper-based crafting system",
    "Designing an efficient minecart rail station with powered and detector rails",
    "Using redstone repeaters and comparators for timing circuits",
    "Using daylight sensors for light-triggered automation",
    "Using target blocks to trigger redstone from a distance",
    "Building a hidden or disguised piston door",
    "Choosing efficient furnace fuel: coal, charcoal, lava buckets, and coal blocks",
    "Finding and looting shipwrecks and buried treasure",
    "Exploring ocean ruins for loot",
    "Surviving an igloo's secret basement",
    "Distinguishing pillager patrols from pillager outposts",
    "Surviving the Nether's crimson and warped forests",
    "Navigating the Soul Sand Valley and avoiding Ghasts",
    "Crossing basalt deltas safely",
    "Exploring End gateways and the outer End islands",
    "Farming chorus fruit in the End",
    "Exploring lush cave biomes for glow berries and spore blossoms",
    "Exploring dripstone caves and avoiding falling stalactites",
    "Surviving frozen peaks and avoiding powder snow",
    "Using a cartography table to extend and lock maps",
    "Using a locator map to find other players",
    "Farming nether wart for potions",
    "Growing and using cocoa beans",
    "Farming sweet berries and glow berries",
    "Using kelp and dried kelp as a renewable fuel source",
    "Understanding Minecraft's difficulty settings and hardcore mode",
    "Choosing between survival, adventure, and spectator game modes",
    "Understanding the keepInventory setting and death item recovery",
    "Choosing the most profitable villager trades for emeralds",
    "Building and using an ender chest for cross-base storage",
    "Using boats and minecarts with attached chests or hoppers",
    "Building an automated melon and pumpkin farm",
    "Farming mushrooms and building a giant mushroom farm",
    "Setting up a cactus and bamboo farm for fuel and green dye",
    "Building a moss and bone meal farm for terraforming",
    "Farming sea pickles and coral for decoration",
    "Setting up a froglight farm with frogs and tadpoles",
    "Building a honey and honeycomb farm with bees",
    "Farming turtle eggs and scutes",
    "Setting up an automatic egg farm with chickens and hoppers",
    "Building a wool farm with automatic sheep shearing",
    "Farming string and spider eyes from a spider spawner",
    "Curing a zombie villager back into a villager for cheap trades",
    "Leading and transporting mobs with leads and boats",
    "Using name tags to prevent mobs from despawning",
    "Equipping and controlling a wolf pack in combat",
    "Riding and controlling a pig or strider with a saddle",
    "Getting a parrot to sit on your shoulder",
    "Understanding mob spawning caps and mob density limits",
    "Converting mobs: creeper to charged creeper, and villager to witch",
    "Assigning villager professions with job site blocks",
    "Using an axolotl to help fight underwater guardians",
    "Preventing iron golems and snow golems from taking damage",
    "Understanding how difficulty affects mob equipment and spawns",
    "Brewing and using Potion of Water Breathing for underwater work",
    "Brewing and using Potion of Fire Resistance for the Nether",
    "Brewing and using Potion of Night Vision for cave exploration",
    "Brewing Potion of Swiftness and Slowness with sugar and turtle shells",
    "Brewing Potion of Strength and Weakness for combat",
    "Extending and amplifying potions with redstone and glowstone",
    "Using a fermented spider eye to corrupt potions",
    "Choosing tool enchantments: Efficiency, Unbreaking, and Mending",
    "Using Frost Walker boots to walk across water",
    "Using Depth Strider and Aqua Affinity for underwater efficiency",
    "Using Feather Falling and Protection to survive big falls",
    "Understanding enchantment level costs and the lapis lazuli requirement",
    "Making concrete, terracotta, and glazed terracotta for colorful builds",
    "Using stairs, slabs, and walls for detailed building",
    "Lighting builds without torches using lanterns and glowstone",
    "Using flower pots, item frames, and armor stands for decoration",
    "Making stained glass and using it in windows",
    "Building with copper: oxidation stages and waxing to lock the patina",
    "Using trapdoors and fence gates as decorative details",
    "Building a functional and safe underground or cave base",
    "Understanding the world height limit and build limit",
    "Understanding how beds set spawn points and skip night",
    "Using bone meal to speed up crop and tree growth",
    "Understanding redstone signal strength and the 15-block limit",
    "Understanding game ticks, redstone ticks, and game speed",
    "How chunk loading and the simulation distance affect farms",
    "Spawn-proofing an area with light and slabs",
    "Understanding random ticks and how they drive crop and fire spread",
    "Understanding the mob spawning cycle and the 24-block spawn sphere",
    "How the difficulty of regional spawns scales with time spent in a chunk",
    "Understanding hopper transfer rates and item throughput limits",
    "Using scheduled ticks and block updates in redstone timing",
    "Understanding fall damage and how to negate it with water or hay",
    "Building a conduit and powering it for underwater mining",
    "Fighting and farming drowned for tridents and nautilus shells",
    "Breeding and farming dolphins' grace for fast swimming",
    "Finding and using heart of the sea and nautilus shells",
    "Setting up an underwater base with air pockets and doors",
    "Farming pufferfish, tropical fish, and other fish types",
    "Using a bucket of fish to relocate and stock aquariums",
    "Collecting sea lanterns, prismarine, and prismarine bricks",
    "Navigating and mapping ocean biomes: warm, cold, and frozen",
    "Using turtle shells for water breathing and turtle master potions",
    "Looting the different bastion remnant types safely",
    "Fighting and farming hoglins for porkchops and leather",
    "Avoiding zoglins and understanding hoglin repellents",
    "Building a gold farm on a nether roof with zombified piglins",
    "Farming magma cubes for magma cream",
    "Building a wither rose farm from mob deaths",
    "Using warped fungus to repel hoglins and control striders",
    "Finding and mining nether gold ore and nether quartz",
    "Setting up a piglin bartering farm for endless loot",
    "Growing a nether tree farm from crimson and warped nylium",
    "Using a spyglass to scout distant terrain and mobs",
    "Using a brush for archaeology on suspicious sand and gravel",
    "Organizing your inventory with bundles",
    "Using a clock and compass to track time and spawn direction",
    "Using a recovery compass to find your last death location",
    "Using flint and steel versus fire charges",
    "Using shears for wool, leaves, and honeycomb collection",
    "Using a fishing rod as a tool to pull mobs and items",
    "Writing and copying books with a book and quill",
    "Choosing the right pickaxe tier for each ore and block",
    "Choosing between regular and sticky pistons for a build",
    "Using dispensers versus droppers for automation",
    "Wiring buttons, levers, and pressure plates as inputs",
    "Using tripwire hooks to build trap and detection circuits",
    "Tuning note block pitch and instrument by the block underneath",
    "Building a T flip-flop toggle with redstone",
    "Building logic gates: AND, OR, NOT, and XOR in redstone",
    "Using redstone lamps and how to keep them lit or pulsing",
    "Using a lectern and comparator to read book pages as a signal",
    "Reading container fullness with a comparator",
    "Understanding ore distribution by Y-level after the cave update",
    "Mining deepslate ores and dealing with their extra hardness",
    "Branch mining versus cave mining for efficiency",
    "Mining safely around lava at deep Y-levels",
    "Using TNT or bed explosions for fast bedrock-level mining",
    "Smelting raw iron, copper, and gold ore versus block crafting",
    "Reading an ore's block texture to tell deepslate from stone variants",
    "Using a Fortune pickaxe to multiply coal, lapis, and redstone drops",
    "Reaching and mining amethyst geodes for shards and blocks",
    "Surviving the first night with minimal resources",
    "Punching your first tree and crafting basic wooden tools",
    "Making a bed early to skip the dangerous first nights",
    "Finding food fast on day one without a farm",
    "Building a safe starter shelter before nightfall",
    "The order to craft your first crafting table, furnace, and chest",
    "Getting from wood tools to stone to iron efficiently",
    "Finding coal and making torches early",
    "Making charcoal from wood when you can't find coal",
    "Gathering wool for a bed from sheep or spider string",
    "Getting the Hero of the Village discount after winning a raid",
    "Locking in a villager's trades before leveling them up",
    "Rerolling a villager's trades by breaking and replacing its job block",
    "Leveling villagers from novice to master for better trades",
    "Defending a village from zombie sieges to protect villagers",
    "Moving villagers safely with minecarts or boats",
    "Setting up a mending-book librarian for cheap repairs",
    "Understanding trade demand and price fluctuation",
    "Building a nether-portal-based villager restock loop",
    "Getting the cleric, armorer, and toolsmith trades you need",
    "How thunderstorms create charged creepers and channeling strikes",
    "Using lightning rods to protect wooden builds from fire",
    "How rain affects fishing, fire, and mob behavior",
    "How weather and biome temperature affect snow and ice formation",
    "Understanding day/night cycle length and phases",
    "How moon phases affect slime spawns and mob stats",
    "Managing fire spread and using fire-resistant blocks",
    "How biome affects mob types, grass color, and weather",
    "Using powder snow to safely descend or trap mobs",
    "How crops need light and water to grow and mature",
    "Building a slabs-and-pistons seven-segment display",
    "Building a combination lock with levers or item frames",
    "Building an automatic bridge or staircase with slime blocks",
    "Building a bamboo-and-piston auto-smelter feed system",
    "Building a piston-tower bolt lift for moving up quickly",
    "Building a mob switch to reduce lag and control spawns",
    "Building a chunk loader with a nether portal and minecart",
    "Building an automatic bell or alarm triggered by mobs",
    "Building a self-building or self-repairing wall with pistons",
    "Building a compact automatic storage silo with overflow protection",
    "Curing poison, wither, and hunger status effects",
    "Using milk to clear all status effects in an emergency",
    "Managing the hunger bar and how sprinting drains it",
    "How saturation hides behind the hunger bar and delays starving",
    "Using golden apples and golden carrots for their effects",
    "Surviving the levitation effect from a shulker attack",
    "Using beacon regeneration and resistance for tough fights",
    "Recovering health quickly with food, regeneration, and natural regen",
    "Using slowness and glowing effects from arrows in combat",
    "Understanding how armor points and toughness reduce damage",
    "Building an ice boat highway for fast overland travel",
    "Using the Nether's 8:1 ratio for fast overworld travel",
    "Spacing redstone-torch boosters to keep a long rail line powered",
    "Using ender pearls for quick short-distance teleports",
    "Setting up a bubble column for fast vertical item and player transport",
    "Building a horse-and-fence stable for stored mounts",
    "Choosing between elytra, horse, boat, and minecart for a trip",
    "Building an automated item transport line with water streams",
    "Building a boat dispenser dock for repeated water launches",
    "Launching yourself long distances with a TNT or wind-charge jump",
    "Building an enderman farm in the End for ender pearls and XP",
    "Farming ghast tears from ghasts in the Nether",
    "Farming phantom membranes for slow falling potions and elytra repair",
    "Farming slimeballs from slimes for sticky pistons and leads",
    "Farming ink sacs from squid and glow ink from glow squid",
    "Farming gunpowder from creepers for TNT and rockets",
    "Farming bones and arrows from a skeleton spawner",
    "Farming rotten flesh from a zombie spawner for trading",
    "Collecting rabbit hide, rabbit's foot, and rabbit stew ingredients",
    "Farming redstone and glowstone dust from witch drops",
    "Finding and looting a swamp witch hut",
    "Turning a dungeon spawner room into a mob farm",
    "Looting a ruined portal for gold and enchanted gear",
    "Exploring abandoned mineshafts and avoiding cave spider spawners",
    "Excavating trail ruins for pottery sherds and armor trims",
    "Finding buried desert wells and fossils",
    "Distinguishing the different village biome styles and layouts",
    "Setting up a lodestone and compass for a permanent waypoint",
    "Harvesting soul soil and making soul torches and campfires",
    "Collecting mob heads and skulls for decoration",
    "Finding flowers and crafting the full set of 16 dyes",
    "Dyeing wool, beds, carpets, and banners a chosen color",
    "Growing a flower farm with bone meal for dye supply",
    "Making white dye from bone meal and other primary dyes",
    "Combining dyes to mix secondary and tertiary colors",
    "Dyeing leather armor and shulker boxes",
    "Building pixel art with wool or concrete blocks",
    "Making and placing candles and dyeing them",
    "Dyeing a tamed wolf's or cat's collar",
    "Making tinted glass and its light-blocking property",
    "Crafting firework rockets with different flight durations",
    "Making firework stars with shapes, colors, and fade effects",
    "Finding an elytra in an End ship and repairing it",
    "Making a firework display with dispensers and a timer",
    "Using multishot and piercing crossbow enchantments",
    "Using firework rockets as a weapon from a crossbow",
    "Building a launch pad for taking off with elytra",
    "Timing rocket boosts to fly efficiently without crashing",
    "Using slow falling potions to survive long drops",
    "Gliding down from high places without a rocket",
    "Collecting all the music discs and where each one drops",
    "Getting the dragon egg down after the Ender Dragon fight",
    "Crafting a nether star into a beacon after a Wither kill",
    "Completing the 'Adventuring Time' all-biomes advancement",
    "Completing the 'A Balanced Diet' eat-everything advancement",
    "Completing the 'Monsters Hunted' kill-every-mob advancement",
    "Building a full trophy or collection display room",
    "Collecting every banner pattern and painting variant",
    "Getting echo shards from an Ancient City",
    "Completing the full advancement tree as an end goal",
    "Crafting and equipping wolf armor to protect a pet wolf",
    "Finding the different wolf variants by biome",
    "Fitting a horse with horse armor and a saddle",
    "Breeding a donkey and horse to get a mule for chest storage",
    "Attracting and taming the different cat variants from villages",
    "Equipping a llama with a decorative carpet and forming a caravan",
    "Growing a baby mob to adulthood faster with its breeding food",
    "Getting the rare brown panda or other panda gene traits",
    "Finding all the axolotl color variants including the rare blue",
    "Finding and taming a skeleton horse from a skeleton trap",
    "Getting a mooshroom and shearing it into a cow for mushrooms",
    "Building a medieval castle with walls and towers",
    "Designing a modern house with large windows and clean lines",
    "Building a treehouse in a large jungle or oak tree",
    "Making fake furniture like chairs, tables, and sofas from blocks",
    "Adding a roof with the right slope using stairs and slabs",
    "Landscaping with dirt paths, leaves, and custom trees",
    "Building a water fountain or koi pond as a centerpiece",
    "Terraforming hills and cliffs to look natural",
    "Choosing a build palette that mixes complementary block textures",
    "Building a functional greenhouse with glass and crops",
    "Using the /gamerule command to tweak world behavior",
    "Using /give and /summon in creative to spawn items and mobs",
    "Setting a world border with the /worldborder command",
    "Using /time and /weather to control day and storms",
    "Using /tp and coordinates to move around a world",
    "Enabling and using cheats and command blocks in a world",
    "Using structure blocks to save and load builds",
    "Using spawn eggs and the creative inventory efficiently",
    "Using /locate to find the nearest structure or biome",
    "Backing up and copying a single-player world safely",
    "Cooking and comparing steak, porkchop, and mutton",
    "Making bread, cakes, and cookies from wheat and cocoa",
    "Making dried kelp as a cheap fast-eating snack",
    "Crafting rabbit stew, beetroot soup, and mushroom stew",
    "Making pumpkin pie and other festive foods",
    "Making suspicious stew and its temporary effects",
    "Deciding which foods to avoid: pufferfish, spider eyes, and rotten flesh",
    "Building a smoker for faster food cooking",
    "Cooking food passively on a campfire",
    "Making a honey bottle and using it to cure poison",
    "Setting up and whitelisting a small multiplayer server",
    "Designing a fair PvP arena with balanced gear and kits",
    "Protecting a shared spawn area from griefing",
    "Splitting roles on a survival multiplayer team",
    "Coordinating a group Wither or Ender Dragon fight",
    "Agreeing on server rules and claiming land to avoid conflicts",
    "Playing on an anarchy or hardcore-rules server safely",
    "Setting up sleep voting so one player can skip the night",
    "Sharing coordinates and setting up a base network with teammates",
    "Running a minigame like spleef or parkour for friends",
    "Timing crop replanting to maximize a farm's output per hour",
    "Deciding when to explore versus when to consolidate a base",
    "Reading the debug screen (F3) to find coordinates and biome",
    "Recovering from losing all your gear in lava or the void",
    "Prioritizing which tools to enchant first with limited experience",
    "Planning a base layout around future automation and expansion",
    "Managing inventory space on a long mining or exploration trip",
    "Deciding between a mob farm and manual grinding for experience",
    "Preparing supplies and gear before a long Nether expedition",
    "Choosing where to dig your first mine shaft for safety and yield",
    "Balancing exploration risk against the value of the loot ahead",
    "Setting up a bed and respawn strategy before a dangerous fight",
    "Deciding when a farm is worth automating versus doing by hand",
    "Scaling a starter base into a functional multi-system hub",
    "Judging when your gear is strong enough to fight the Warden",
    "Choosing a renewable food source that fits your playstyle",
    "Sequencing early-game goals from first night to full iron gear",
    "Recognizing and escaping a cave-in or lava-flow emergency",
    "Deciding whether to cure a zombie villager or find a village",
    "Weighing the cost of a beacon against its practical benefits",
]


def archetypes_for(category: str) -> List[Callable[[Dict[str, Any]], str]]:
    return ARCHETYPES.get(category, [])


def pick_archetype(category: str, rng) -> Callable[[Dict[str, Any]], str]:
    options = archetypes_for(category)
    if not options:
        raise ValueError(f"No archetypes registered for category {category!r}")
    return rng.choice(options)


def pick_free_recall_topic(rng) -> str:
    return rng.choice(FREE_RECALL_TOPICS)
